### ISSUE TITLE
score incorrectly displayed in Invader Overload

### ISSUE THREAD

**Issue by gingerbeardman** [gamax92/picolove#9] opened 2016-08-08 12:20 UTC
Invader Overload
http://www.lexaloffle.com/bbs/?tid=4004
http://www.lexaloffle.com/bbs/cposts/2/26413.p8.png

![screen shot 2016-08-08 at 12 28 47](https://cloud.githubusercontent.com/assets/49612/17478907/fb57c946-5d66-11e6-9162-ea00f2203ada.png)

problem is with this code:
http://www.lexaloffle.com/bbs/?tid=3577

``` lua
-- print out score text from large number
function score_text(val)
   local s = ""
   local v = abs(val)
   while (v!=0) do
     s = shl(v % 0x0.000a, 16)..s
     v /= 10
   end
   if (val<=0)  s = "0"..s
   return s
end
```

**Comment by gamax92** [comment] 2016-08-09 18:33
Yeah I've noticed this too, I'll look into it, thanks for reporting!

**Comment by gamax92** [comment] 2016-08-12 01:24
So, I'm not sure how fixable this is. The issue is because with fixed point, dividing by 10 will quickly drop a number down to zero.
With a double however, it takes much longer to constantly divide out, going all the way to e-323 before hitting zero.

**Comment by gingerbeardman** [comment] 2016-08-12 12:26
Hmm. I guess if a game uses functionality like this, it's probably better to remove it from the game as picolove doesn't suffer from the lower number accuracy it's trying to workaround?

**Comment by gamax92** [comment] 2016-08-12 17:24
I'm not quite sure what you meant by that?

**Comment by gingerbeardman** [comment] 2016-08-12 21:56
I mean that if I wanted to port a game to picolove thst used this large number workaround, I'd just replace it as it's not needed. 

For Invader Overload I only had to change a few lines to bypass this function and get scoring working.

**Comment by gamax92** [comment] 2016-08-13 00:27
Understandable. For now I guess I'll close this as not fixable.

**Closed as completed by gamax92** 2016-08-13 00:27 UTC
Labels: wontfix
